### PR TITLE
Replace spotify/docker-client with docker-java/docker-java

### PR DESCRIPTION
**Pull request by thyming**
### Purpose of changes
Replace the docker client with https://github.com/docker-java/docker-java
This skirts various issues that the existing docker client has and reduces the dependency surface.
See #96 .

### Types of changes

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### How has this been tested?

Tests pass, I've tried this on a project of mine and it works where the last published version does not.

### CODE REVIEW

**Comment by thyming** [comment]
Any chance you could cut at least a prerelease with this commit? Thanks!

**Comment by bonigarcia** [comment]
Not yet, sorry. Further changes are required to make a release since this patch has broken the build:

https://travis-ci.org/github/bonigarcia/selenium-jupiter/builds/755326972

Please feel free to commit more PR to fix the broken tests, if you want.

**Comment by thyming** [comment]
```Error response from daemon: No such image: selenoid/video-recorder:latest-release```
This class of error is responsible for at least one of the test failures, and looking at the code I'm not sure how it relates to my changes. Regardless, why is this stored in preferences? Is there any risk in unconditionally pulling the supporting images? If a user wants/needs the build to be reproducible wrt the images used by this extension, I'd think they should configure it specifically with the configuration variables already in place.

**Comment by stevej2** [comment]
This sounds related to an issue/question I raised. I am trying to use this on a standalone system. All images already pulled but no connection to internet. 

I have to retag the local video-recorder image e.g. from xxx:7.1 to xxx:latest-release to avoid errors. 

I am however still getting issues where it fails when the docker service tries to check for new image, despite it already existing locally

**Comment by bonigarcia** [comment]
The problem was in the logic for pulling the images (it was missing the await completion invocation). Now it is fixed. It will be available for the next version (to be released soon, stay tuned).

**Pull request merged**
